### ISSUE TITLE
Credetials for docker container

### ISSUE THREAD

**Issue by Marf97** [hpilo-exporter/hpilo-exporter#3]
Hi, 

I wanted to ask if there is any way how to pass iLo credentials in safer way then just env variables? When I will be runing this in kubernetes cluster and I have for example HashiCorp Vault is there a way that this container can obtain configuration from vault? Thank you for the answer.

**Comment by Marf97** [comment]
@srkaviani Are you handling credentials to iLo machines in any safe way? I'm open to suggestions

**Comment by srkaviani** [comment]
Hi,
the way you can use for handling ilo credentials is set the ilo_user and ilo_pass in prometheus.yml file.
or you can set the ilo credentials in exporter env:
` docker run -p 9416:9416 hpilo-exporter:latest --port 9416 --ilo_user my_user --ilo_password my_secret_password `
now I don't have any idea for handling credentials in safer way but usually ILO hosts only have private ip and not available in public environment, So there is nothing to worry about.

**Comment by Marf97** [comment]
You are right, if the iLO user doesn't have any permissions, it can just read metrics so I won't consider this an issue anymore
