### ISSUE TITLE
suggestion: hpilo_exporter.service

### ISSUE THREAD

**Issue by fe-berg** [hpilo-exporter/hpilo-exporter#6]
Hello everyone,
thank you so much for your project. after 2 weeks of trying to use checkmk and a connector to grafana, the snmp-exporter and it's generator and not having the MiB files for it i finally found this project with python3 and after a few tries i got it running in my enviroment.

i am now in the process of creating a .service file to have the exporter run in the background.
i think it would be a great addition to your project for future people in need.

kind regards and thanks again for your work
Felix

**Comment by srkaviani** [comment]
Hi
after your suggestion i have added _hpilo-exporter.service_ and install.sh script in this Pull Request:
#7 

after review by my friends in hpilo-exporter community changes will be merged with main repository.

**Your welcome.**
Soroush

**Comment by srkaviani** [comment]
pull request #7 has been merged .
